force-app/main/default/objects/Feature_Flag__mdt/fields/Rollout_Type__c.field-meta.xml
<CustomField>
    <fullName>Rollout_Type__c</fullName>
    <label>Rollout Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Permission</fullName>
                <default>true</default>
                <label>Custom Permission</label>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feature_Flag__mdt/fields/Rollout_Value__c.field-meta.xml
<CustomField>
    <fullName>Rollout_Value__c</fullName>
    <inlineHelpText>Not applicable for Enabled/Disabled.
Add Single or Comma Seperated values for multiple checks.</inlineHelpText>
    <label>Rollout Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Strategies/FeatureType_CustomPermissionTest.cls
@isTest
public with sharing class FeatureType_CustomPermissionTest {
    @IsTest
    private static void testCustomPermissionFeatureNegative() {

        Feature_Flag__mdt Mockfeature = new Feature_Flag__mdt();
        Mockfeature.DeveloperName = 'TestCustomPermission';
        Mockfeature.Rollout_Type__c = 'Custom Permission';
        Mockfeature.MasterLabel = 'Test Custom Permission';
        Mockfeature.Rollout_Value__c = 'SomePermission';

        IFeatureType featureType = (IFeatureType) Type.forName('FeatureType_CustomPermission').newInstance();
        System.assertEquals(false, featureType.status(Mockfeature));
    }
}