force-app/main/default/objects/Feature_Flag__mdt/fields/Rollout_Type__c.field-meta.xml
<CustomField>
    <fullName>Rollout_Type__c</fullName>
    <label>Rollout Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Permission</fullName>
                <default>true</default>
                <label>Custom Permission</label>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Core/FeatureTest.cls
@isTest
private class FeatureTest {

    @isTest
    private static void testFeature() {
        Feature_Flag__mdt Mockfeature = new Feature_Flag__mdt();
        Mockfeature.MasterLabel = 'Test Flag True';
        Mockfeature.DeveloperName = 'Test_Flag_True';
        Mockfeature.Rollout_Type__c = 'Enabled';
        FeatureFlag.mockedMetadata = Mockfeature;
        System.AssertEquals(true, Feature.isActive('Test Flag True')); //Integration Testing with Mock Data
        System.AssertEquals(true, Feature.FeatureCache.get('Test Flag True')); //Cache Hit Testing
        System.AssertEquals(true, Feature.featureStatus('Test Flag True')); //LWC Function Testing
    }
}