force-app/main/default/objects/Feature_Flag__mdt/fields/Rollout_Type__c.field-meta.xml
<CustomField>
    <fullName>Rollout_Type__c</fullName>
    <label>Rollout Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Permission</fullName>
                <default>true</default>
                <label>Custom Permission</label>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Strategies/FeatureType_EnabledDisabledTest.cls
@isTest
public with sharing class FeatureType_EnabledDisabledTest {
    @IsTest
    private static void testEnabledFeature() {

        Feature_Flag__mdt Mockfeature = new Feature_Flag__mdt();
        Mockfeature.DeveloperName = 'TestGlobalEnabled';
        Mockfeature.Rollout_Type__c = 'Enabled';
        Mockfeature.MasterLabel = 'Test Global Enabled';
        IFeatureType featureType = (IFeatureType) Type.forName('FeatureType_Enabled').newInstance();
        System.assertEquals(true, featureType.status(Mockfeature));
    }

    @IsTest
    private static void testDisabledFeature() {

        Feature_Flag__mdt Mockfeature = new Feature_Flag__mdt();
        Mockfeature.DeveloperName = 'TestGlobalDisabled';
        Mockfeature.Rollout_Type__c = 'Disabled';
        Mockfeature.MasterLabel = 'Test Global Disabled';
        IFeatureType featureType = (IFeatureType) Type.forName('FeatureType_Disabled').newInstance();
        System.assertEquals(false, featureType.status(Mockfeature));
    }

}