force-app/main/default/objects/Feature_Flag__mdt/fields/Rollout_Type__c.field-meta.xml
<CustomField>
    <fullName>Rollout_Type__c</fullName>
    <label>Rollout Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Permission</fullName>
                <default>true</default>
                <label>Custom Permission</label>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FeatureFlagTest.cls
@isTest
public with sharing class FeatureFlagTest {
    
    @IsTest
    private static void testFeature() {

        Feature_Flag__mdt Mockfeature = new Feature_Flag__mdt();

        System.AssertEquals(false, FeatureFlag.evaluate('InvalidFeature')); //Integration Testing with invalid data

        Mockfeature.DeveloperName = 'TestFlagTrue';
        Mockfeature.Rollout_Type__c = 'Enabled';
        FeatureFlag.mockedMetadata = Mockfeature;

        System.AssertEquals(true, FeatureFlag.evaluate('TestFlagTrue')); //Integration Testing with Mock Data
        System.AssertEquals(true, FeatureFlag.evaluate('TestFlagTrue')); //Cache Testing with Mock Data
    }
}