force-app/main/default/objects/Feature_Flag__mdt/fields/Rollout_Value__c.field-meta.xml
<CustomField>
    <fullName>Rollout_Value__c</fullName>
    <inlineHelpText>Not applicable for Enabled/Disabled.
Add Single or Comma Seperated values for multiple checks.</inlineHelpText>
    <label>Rollout Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Feature Flagging Framework/FeatureType_ProfileBased.cls
public with sharing class FeatureType_ProfileBased implements IFeatureType{
    static string userProfileName;
    Static Map<String, Boolean> profileCache = new Map<String, Boolean>();
    public Boolean status(Feature_Flag__mdt feature) {
        
        if(userProfileName==null){
            userProfileName = [SELECT profile.Name FROM User WHERE Id = :UserInfo.getUserId()].profile.Name;
        }

        if (profileCache.containsKey(userProfileName)) {
            return profileCache.get(userProfileName);
        }

        Set<String> profiles = new Set<String>(feature.Rollout_Value__c.split(','));
        Boolean isActive = profiles.contains(userProfileName);
        profileCache.put(userProfileName, isActive);
        return isActive;
    }
}